### ISSUE TITLE
Upgrade `Create GitHub Release` to non-deprecated version 

### ISSUE THREAD

**Issue by nooikko** [garronej/ts-ci#11]
Warnings provided by GitHub during action run:
![image](https://user-images.githubusercontent.com/10214170/201413658-37efc3f3-bfbe-4386-a031-e23501da735e.png)

Code in Question:
https://github.com/garronej/ts-ci/blob/main/.github/workflows/ci.yaml

Line 65: create_github_release

**Comment by garronej** [comment]
Hey @nooikko,  

Sorry about the warnings.  
GitHub deprecated `set-output` about a month ago an all the ecosystem of actions aven't mooved on yet.  

In particular, here I'm waiting for this issue to be addressed:  
https://github.com/softprops/action-gh-release/issues/268  

If the maintainer of `action-gh-release` dosen't update I'll be looking for an alternative action.  

Thanks for reporting anyway.
